# https://cmake-format.readthedocs.io/en/latest/
format:
  line_width: 100
  tab_size: 2
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 3
  max_rows_cmdline: 1
  dangle_parens: true
  dangle_align: "prefix"
  min_prefix_chars: 2
  max_prefix_chars: 4
  max_lines_hwrap: 1
  command_case: "lower"
  keyword_case: "upper"
markup:
  enable_markup: false
